# Generated by Django 3.2.5 on 2021-07-17 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(default=django.utils.timezone.now)),
                ('identificacao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('auto_infracao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reclamante', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reclamada', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ficha_de_atendimento', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_de_situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('css_cor', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['ordem', 'nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Situcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes', to='api.processo')),
                ('tipo_de_situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes', to='api.tipo_de_situacao')),
            ],
            options={
                'ordering': ['processo', 'data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
