# Generated by Django 3.2.5 on 2021-07-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210717_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situcacao',
            options={'ordering': ['processo', 'data', 'id'], 'verbose_name_plural': 'Situcacoes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_de_situacao',
            options={'ordering': ['ordem', 'nome', 'id'], 'verbose_name_plural': 'Tipo_de_situacoes'},
        ),
        migrations.AlterField(
            model_name='tipo_de_situacao',
            name='ordem',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
