# Generated by Django 3.2.5 on 2021-07-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_processo_criado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situcacao',
            old_name='observacao',
            new_name='comentario',
        ),
    ]
