# Generated by Django 3.2.5 on 2021-07-23 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_observacao_situcacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situcacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
