# Generated by Django 3.2.5 on 2021-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comentariodocumento_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
