# Generated by Django 3.2.5 on 2021-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_documento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
